#!/bin/bash
cd /opt/ixpcontrol/data/routeserver/PEERS;
rm -rf /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v4.conf;
rm -rf /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v6.conf;
echo "IPv4 Generation"
echo "define PREFIX_BGPEX = [" > /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v4.conf;
for v4ASN in *; do
    if [ -d "$v4ASN" ]; then
                echo "Found ASN: $v4ASN"
                if [[ -e /opt/ixpcontrol/data/routeserver/PEERS/$v4ASN/prefix_v4.conf ]]; then
			for CT in $(tail -n +2 /opt/ixpcontrol/data/routeserver/PEERS/$v4ASN/prefix_v4.conf | head -n-1 | sed 's/,//g' | sed 's/    //g')
			do
			echo $CT","  >> /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v4.conf
			done
                fi
    fi
done
echo "];" >> /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v4.conf;
sed 'x;${s/,$//;p;x;};1d' /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v4.conf
echo "IPv6 Generation"
echo "define PREFIX_BGPEX = [" > /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v6.conf;
for v6ASN in *; do
    if [ -d "$v6ASN" ]; then
                echo "Found ASN: $v6ASN"
                if [[ -e /opt/ixpcontrol/data/routeserver/PEERS/$v6ASN/prefix_v6.conf ]]; then
                        for CT in $(tail -n +2 /opt/ixpcontrol/data/routeserver/PEERS/$v6ASN/prefix_v6.conf  | head -n-1 | sed 's/,//g'  |sed 's/    //g')
                        do
                        echo $CT","  >> /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v6.conf
                        done
                fi
    fi
done
echo "];" >> /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v6.conf;
sed 'x;${s/,$//;p;x;};1d' /opt/ixpcontrol/data/routeserver/PREFIX/prefixes_v6.conf
